{"message":"response error to user","stack":"ValidationError: error validating parm, path:username,reason: duplicate user name: qiuzhaoyang111\n    at user.save.catch.e (G:\\one_punch\\modles\\mongo\\user.js:37:19)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:169:7)","OPCode":2000000,"httpCode":400,"httpMsg":"这个昵称已经存在,换一个吧~~~","name":"ValidationError","level":"error","timestamp":"2017-08-18T06:31:50.528Z"}
{"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: one_punch.users index: name_1 dup key: { : \"qiuzhaoyang111\" }","op":{"password":"��j��\u0007�钩�]��������\u00052��$\u0012o�y�Y���j\u001f\u0017? 8�Br�o�>�#\n`! #�8�QF�\u001dJ��\n�ˁ��B��/n9\u0012ߘO��\u001eW�����ʻ� \n\u000f��_,\u0004Ζ���8Ğ����w\u001b\u000f�J\u001cF����,�","name":"qiuzhaoyang111","age":33,"phoneNumber":"18552065308","_id":"59968adbf66e41174c66feb1","__v":0}}
{"message":"response error to user","stack":"ValidationError: error validating parm, path:username,reason: duplicate user name: qiuzhaoyang111\n    at user.save.catch.e (G:\\one_punch\\modles\\mongo\\user.js:39:19)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:169:7)","OPCode":2000000,"httpCode":400,"httpMsg":"这个昵称已经存在,换一个吧~~~","name":"ValidationError","level":"error","timestamp":"2017-08-18T06:36:11.475Z"}
